dist: trusty
sudo: false
language: node_js
node_js: lts/*

install:
  - npm run add-fa-config
  - npm ci
cache:
  directories:
  - $HOME/.npm

script:
- npm run build
- npm run build:demo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/ng-wizard-demo
    on:
      all_branches: true

git:
  depth: 3

after_success:
- npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
  - /^v\d+\.\d+\.\d+$/
